# NUMERICAL PYTHON (NUMPY)

In [37]:
import numpy as np 

# import the NumPy library with the 'np'

### Normalization Problem

In [38]:
X = np.random.rand (5, 5) # create a 5x5 array filled with random float numbers between 0 and 1
print ("Original array X:") # label and print to indicate the original (unnormalized) array
print (X) # print the contents of the array X

Original array X:
[[0.1776342  0.57704216 0.23915709 0.96082686 0.73985412]
 [0.4339007  0.05191411 0.61247685 0.54095802 0.67134365]
 [0.12890651 0.06126694 0.18407051 0.31359245 0.80190885]
 [0.87789692 0.53974643 0.81134419 0.37634833 0.77633622]
 [0.53949434 0.75783353 0.42785424 0.65036754 0.46056141]]


In [39]:
X_normalized = (X - X.mean()) / X.std() # normalize X using the formula Z = (X - mean) / std
print("\nNormalized array X:") # label and print to indicate that the contents are the Normalized Array
print(X_normalized) # print the array


Normalized array X:
[[-1.27594555  0.26429953 -1.03869359  1.74429631  0.89215463]
 [-0.28769981 -1.76076253  0.40094704  0.1251475   0.6279563 ]
 [-1.46385513 -1.72469499 -1.25112509 -0.75164698  1.13145756]
 [ 1.42449191  0.12047526  1.16784325 -0.50964018  1.03284127]
 [ 0.11950311  0.96148898 -0.31101691  0.54706567 -0.18488756]]


In [40]:
np.save('X_normalized.npy', X_normalized) # save the normalized array with the file name X_normalized.npy
print("\nNormalized array saved as 'X_normalized.npy'") # print to confirm that the file has been saved


Normalized array saved as 'X_normalized.npy'


### Divisible by 3 Problem

In [45]:
A = (np.arange(1, 101) ** 2).reshape(10, 10) # square each element then reshape the result into a 10x10 2D array which is a matrix
print("Array A (squares of first 100 integers):") # label and print the matrix
print(A) # print the contents of the matrix

Array A (squares of first 100 integers):
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [46]:
div_by_3 = A[A % 3 == 0] # find all elements in the matrix that are divisible by 3
print("\nElements divisible by 3:") # label and print to indicate the elements that are divisible by 3
print(div_by_3) # print all the values that are divisible by 3


Elements divisible by 3:
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [47]:
np.save('div_by_3.npy', div_by_3) # save the values that are divisible by 3 with the file name div_by_3.npy
print("\nDivisible by 3 elements saved as 'div_by_3.npy'") # print to confirm that the file has been saved


Divisible by 3 elements saved as 'div_by_3.npy'
